/*
C++ control structures: (These are the basic control structures)
1- Sequence structures=> Entry -> Action1 -> Action2 -> so on -> Exit
2- Selection structure=> Entry -> Check condition -> if true then Action1, else false then Action2 -> Exit
3- Loop structure=> Entry -> Loop -> Check condition -> if true then Action1 -> Loop again -> when false then Action2 -> Loop breaks -> Exit
*/

#include <iostream>
using namespace std;

// Today we will be learning about Selection Control Statements, i.e., if-else statements
/* It can be executed in 3 ways:
1- If else statement
2- If else ladder(Multiple 'if' then 'else if' then finally 'else')
3- *****Switch case statements*****
*/

int main()
{
    int age;
    cout << "Tell me your age- ";
    cin >> age;
    // if else ladder
    if ((age < 18) && (age > 0))
    {
        cout << "You cannot come to my party." << endl;
    }
    else if (age == 18)
    {
        cout << "You will get a kid pass lol!" << endl;
    }
    else if (age < 0)
    {
        cout << "You are not yet born" << endl;
    }
    else
    {
        cout << "You can come to my party!!" << endl;
    }

    // Switch case statements
    switch (age) // This is generated by switch snippet by VS Code
    {
    case 18:
        cout << "You are 18" << endl;
        break; // If we dont use break it will print neeche ke bhi cout

    case 22:
        cout << "You are 22" << endl;
        break;

    case 5:
        cout << "You are 5" << endl;
        break;

    default:
        cout << "No special cases" << endl;
        break;
    }

    return 0;
}